# Generated by Django 4.0.3 on 2023-11-24 04:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_userclassification_customuser_user_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_nick_name',
            field=models.CharField(default='temp_username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
